### ISSUE TITLE
Library of NURobotics

### ISSUE THREAD

**Issue by jschultehullern** [xman4242/PS4-ESP32-Bluetooth#1]
Hi xman4242,

i want to pair my ps4-controller with an esp32 and want to use your library.
If i want to load the Library of NURobotics, I get a 404 Error.
Do you know where I can find the Library?

Thank you :)

**Comment by xman4242** [comment]
It seems to have vanished. I have the files on my machine, so I duplicated their repo [here.](https://github.com/xman4242/PS4-ESP32) This should work for you. If it doesn't, I may not have the right version. Please let me know if you have trouble.

**Comment by xman4242** [comment]
Shortly after writing this, I realized that the library has not disappeared, only moved. Here is the new link. https://github.com/openobjects/PS4-esp32

**Comment by jschultehullern** [comment]
Thank you :)

If I include your Library to my ArduinoIDE und want to compile a sample I get an Error
![image](https://user-images.githubusercontent.com/14196430/83843465-4dca4c80-a705-11ea-9999-9b450ba58d36.png)

Do you know how to solve it?

**Comment by xman4242** [comment]
That is because my additions are still in progress. I would recommend using this library until it is finished. https://github.com/openobjects/PS4-esp32

**Comment by jschultehullern** [comment]
Okay.

Thank you for your help :)
Now it is working :)

**Comment by xman4242** [comment]
Wonderful! Good luck with your project!
